version: '3'


services:
  pytest:
    build:
      context: .
      dockerfile: compose/local/pytest/Dockerfile
    env_file:
      - ./.envs/.local/.postgres_test
    volumes:
      - ./plugins:/app/plugins
      - ./tests:/app/tests
      - ./scrapy_tasks:/app/scrapy_tasks
    depends_on:
      - postgres

  postgres:
    image: postgres:12.3
    container_name: postgres_crawling_test
    env_file:
      - ./.envs/.local/.postgres_test
    ports:
      - "5434:5432"
    hostname: postgres_crawling_test
