apiVersion: v1
kind: Secret
metadata:
    name: stock-market-secret
type: Opaque
data:
    mongo-root-username: cm9vdA==
    mongo-root-password: cm9vdF9wYXNzd29yZA==
    postgres-password: bmlraTEzMDM5Ng==
